# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  config.vm.box = "ubuntu/xenial64"

  # Multibox configuration
  config.vm.define "leader" do |leader|
	leader.vm.hostname = "leader"
	leader.vm.network "private_network", ip: "10.0.0.11"
  end

  config.vm.define "follower" do |follower|
	follower.vm.hostname = "follower"
	follower.vm.network "private_network", ip: "10.0.0.12"
  end

  config.vm.provision "shell", inline: <<-SHELL
	apt-get install bridge-utils
	apt-get install socat
	sudo apt-get install tshark
	SHELL


end
