# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.hostname = "snmc-node"
  config.vm.network "private_network", ip: "10.0.0.9"
  config.vm.provision "shell", inline: <<-SHELL
	apt-get install bridge-utils
  SHELL
end
